from mujoco_mojo.mjcf.mujoco_attr.sensor_attr.base import SensorBase
from mujoco_mojo.typing import DataType, NeedStage, SensorAttachableName

__all__ = ["SensorUser"]


class SensorUser(SensorBase):
    """
    This element creates a user sensor. MuJoCo does not know how to compute the output of this sensor. Instead the user should install the callback mjcb_sensor which is expected to fill in the sensor data in mjData.sensordata. The specification in the XML is used to allocate space for this sensor, and also determine which MuJoCo object it is attached to and what stage of computation it needs before the data can be computed. Note that the MuJoCo object referenced here can be a tuple, which in turn can reference a custom collection of MuJoCo objects - for example several bodies whose center of mass is of interest.

    If a user sensor is of stage "vel" or "acc", then mj_subtreeVel or mj_rnePostConstraint will be triggered, respectively.
    """

    tag = "user"

    attributes = (
        *SensorBase.attributes,
        "objtype",
        "objname",
        "datatype",
        "needstage",
        "dim",
    )

    objtype: str | None = None
    """Type of the MuJoCo object to which the sensor is attached. This together with the objname attribute determines the actual object. If unspecified, will be mjOBJ_UNKNOWN."""

    objname: SensorAttachableName | None = None
    """Name of the MuJoCo object to which the sensor is attached."""

    datatype: DataType = DataType.REAL
    """The type of output generated by this sensor. "axis" means a unit-length 3D vector. "quat" means a unit quaternion. These need to be declared because when MuJoCo adds noise, it must respect the vector normalization. "real" means a generic array (or scalar) of real values to which noise can be added independently."""

    needstage: NeedStage = NeedStage.ACC
    """The MuJoCo computation stage that must be completed before the user callback mjcb_sensor() is able to evaluate the output of this sensor."""

    dim: int
    """Number of scalar outputs of this sensor."""
