from __future__ import annotations

from typing import ClassVar

import mujoco
import numpy as np

from mujoco_mojo.mjcf.defaults import SOLIMP_DEFAULT, SOLREF_DEFAULT
from mujoco_mojo.mjcf.xml_model import XMLModel
from mujoco_mojo.typing import ContactPairName, GeomName, Vec2, Vec5

__all__ = ["Pair"]


class Pair(XMLModel):
    """This element creates a predefined geom pair which will be checked for collision. Unlike dynamically generated pairs whose properties are inferred from the corresponding geom properties, the pairs created here specify all their properties explicitly or through defaults, and the properties of the individual geoms are not used. Anisotropic friction can only be created with this element."""

    tag = "pair"

    attributes = (
        "name",
        "class_",
        "geom1",
        "geom2",
        "condim",
        "friction",
        "solref",
        "solreffriction",
        "solimp",
        "gap",
        "margin",
        "adhesion",
    )

    _mjt_obj: ClassVar[mujoco.mjtObj | None] = mujoco.mjtObj.mjOBJ_PAIR

    name: ContactPairName | None = None
    """Name of this contact pair."""

    class_: str | None = None
    """Defaults class for setting unspecified attributes."""

    geom1: GeomName
    """The name of the first geom in the pair."""

    geom2: GeomName
    """The name of the second geom in the pair. The contact force vector computed by the solver and stored in mjData.efc_force points from the first towards the second geom by convention. The forces applied to the system are of course equal and opposite, so the order of geoms does not affect the physics."""

    condim: int = 3
    """The dimensionality of the contacts generated by this geom pair."""

    friction: Vec5 = np.array((1, 1, 0.005, 0.0001, 0.0001))
    """The friction coefficients of the contacts generated by this geom pair. Making the first two coefficients different results in anisotropic tangential friction. Making the last two coefficients different results in anisotropic rolling friction. The length of this array is not enforced by the parser, and can be smaller than 5. This is because some of the coefficients may not be used, depending on the contact dimensionality. Unspecified coefficients remain equal to their defaults."""

    solref: Vec2 = SOLREF_DEFAULT
    """Constraint solver parameters for contact simulation. See Solver parameters."""

    solimp: Vec5 = SOLIMP_DEFAULT
    """Constraint solver parameters for contact simulation. See Solver parameters."""

    solreffriction: Vec2 = np.array((0, 0))
    """Contact reference acceleration, in the friction dimensions. This attribute has the same semantics as other solref attributes (described in Solver parameters), with two important distictions:

    - The default "0 0" means "use the same values as solref".
    - This attribute only takes effect for elliptic friction cones, since pyramidal cones mix normal and frictional forces.

    Note that as with other solreffriction attributes, the constraint violation is identically 0. Therefore, when using positive semantics solreffriction[1] is ignored, while for negative semantics solreffriction[0] is ignored. See Solver parameters for more details."""

    margin: float = 0
    """Geometric inflation for the purpose of contact force generation. Contacts are detected at distance `margin + gap` and forces are generated at distance `margin`."""

    gap: float = 0
    """Additional contact detection buffer beyond `margin`. When this value is positive, contacts with distance between `margin` and `margin + gap` are included in `mjData.contact` as inactive contacts but no contact forces are generated."""

    adhesion: float = 0
    """Adhesive force of contacts generated by this pair, overriding the sum of the geoms' adhesion values. See there for detailed semantics."""
