"""Defines child attributes of the Mujoco class."""

from .actuator import Actuator
from .actuator_attr import (
    ActuatorAdhesion,
    ActuatorCylinder,
    ActuatorDamper,
    ActuatorGeneral,
    ActuatorIntegratedVelocity,
    ActuatorMotor,
    ActuatorMuscle,
    ActuatorPlugin,
    ActuatorPosition,
    ActuatorVelocity,
)
from .asset import Asset
from .asset_attr import (
    HField,
    Layer,
    Material,
    Mesh,
    Model,
    Texture,
    TextureBuiltIn,
)
from .body import Body, WorldBody
from .body_attr import (
    Attach,
    Camera,
    Composite,
    CompositeGeom,
    CompositeJoint,
    CompositeSite,
    CompositeSkin,
    FlexComp,
    FreeJoint,
    Geom,
    GeomBox,
    GeomCapsule,
    GeomCylinder,
    GeomEllipsoid,
    GeomHField,
    GeomMesh,
    GeomPlane,
    GeomSDF,
    GeomSphere,
    Inertial,
    Joint,
    Light,
    Site,
    SiteBox,
    SiteCapsule,
    SiteCylinder,
    SiteEllipsoid,
    SiteSphere,
)
from .compiler import Compiler
from .compiler_attr import LengthRange
from .contact import Contact
from .contact_attr import Exclude, Pair
from .deformable import Deformable
from .equality import Equality
from .equality_attr import (
    EqualityConnectBody,
    EqualityConnectSite,
    EqualityFlex,
    EqualityJoint,
    EqualityTendon,
    EqualityWeldBody,
    EqualityWeldSite,
)
from .keyframe import Keyframe
from .keyframe_attr import Key
from .option import Option
from .option_attr import Flag
from .sensor import Sensor
from .sensor_attr import (
    SensorAccelerometer,
    SensorActuatorfrc,
    SensorActuatorpos,
    SensorActuatorvel,
    SensorBallangvel,
    SensorBallquat,
    SensorCamprojection,
    SensorClock,
    SensorContact,
    SensorDistance,
    SensorEKinetic,
    SensorEPotential,
    SensorForce,
    SensorFrameangacc,
    SensorFrameangvel,
    SensorFramelinacc,
    SensorFramelinvel,
    SensorFramepos,
    SensorFramequat,
    SensorFramexaxis,
    SensorFrameyaxis,
    SensorFramezaxis,
    SensorFromto,
    SensorGyro,
    SensorInsidesite,
    SensorJointactuatorfrc,
    SensorJointlimitfrc,
    SensorJointlimitpos,
    SensorJointlimitvel,
    SensorJointpos,
    SensorJointvel,
    SensorMagnetometer,
    SensorNormal,
    SensorPlugin,
    SensorRangefinder,
    SensorSubtreeangmom,
    SensorSubtreecom,
    SensorSubtreelinvel,
    SensorTactile,
    SensorTendonactuatorfrc,
    SensorTendonlimitfrc,
    SensorTendonlimitpos,
    SensorTendonlimitvel,
    SensorTendonpos,
    SensorTendonvel,
    SensorTorque,
    SensorTouch,
    SensorUser,
    SensorVelocimeter,
)
from .size import Size
from .statistic import Statistic
from .tendon import Tendon
from .tendon_attr import (
    Fixed,
    Spatial,
    SpatialGeom,
    SpatialPulley,
    SpatialSite,
    TendonJoint,
)
from .visual import Visual
from .visual_attr import (
    VisualGlobal,
    VisualHeadlight,
    VisualMap,
    VisualQuality,
    VisualRGBA,
    VisualScale,
)

__all__ = [
    "Actuator",
    "ActuatorAdhesion",
    "ActuatorCylinder",
    "ActuatorDamper",
    "ActuatorGeneral",
    "ActuatorIntegratedVelocity",
    "ActuatorMotor",
    "ActuatorMuscle",
    "ActuatorPlugin",
    "ActuatorPosition",
    "ActuatorVelocity",
    "Asset",
    "Attach",
    "Body",
    "Camera",
    "Compiler",
    "Composite",
    "CompositeGeom",
    "CompositeJoint",
    "CompositeSite",
    "CompositeSkin",
    "Contact",
    "Deformable",
    "Equality",
    "EqualityConnectBody",
    "EqualityConnectSite",
    "EqualityFlex",
    "EqualityJoint",
    "EqualityTendon",
    "EqualityWeldBody",
    "EqualityWeldSite",
    "Exclude",
    "Fixed",
    "Flag",
    "FlexComp",
    "FreeJoint",
    "Geom",
    "GeomBox",
    "GeomCapsule",
    "GeomCylinder",
    "GeomEllipsoid",
    "GeomHField",
    "GeomMesh",
    "GeomPlane",
    "GeomSDF",
    "GeomSphere",
    "HField",
    "Inertial",
    "Joint",
    "Key",
    "Keyframe",
    "Layer",
    "LengthRange",
    "Light",
    "Material",
    "Mesh",
    "Model",
    "Option",
    "Pair",
    "Sensor",
    "SensorAccelerometer",
    "SensorActuatorfrc",
    "SensorActuatorpos",
    "SensorActuatorvel",
    "SensorBallangvel",
    "SensorBallquat",
    "SensorCamprojection",
    "SensorClock",
    "SensorContact",
    "SensorDistance",
    "SensorEKinetic",
    "SensorEPotential",
    "SensorForce",
    "SensorFrameangacc",
    "SensorFrameangvel",
    "SensorFramelinacc",
    "SensorFramelinvel",
    "SensorFramepos",
    "SensorFramequat",
    "SensorFramexaxis",
    "SensorFrameyaxis",
    "SensorFramezaxis",
    "SensorFromto",
    "SensorGyro",
    "SensorInsidesite",
    "SensorJointactuatorfrc",
    "SensorJointlimitfrc",
    "SensorJointlimitpos",
    "SensorJointlimitvel",
    "SensorJointpos",
    "SensorJointvel",
    "SensorMagnetometer",
    "SensorNormal",
    "SensorPlugin",
    "SensorRangefinder",
    "SensorSubtreeangmom",
    "SensorSubtreecom",
    "SensorSubtreelinvel",
    "SensorTactile",
    "SensorTendonactuatorfrc",
    "SensorTendonlimitfrc",
    "SensorTendonlimitpos",
    "SensorTendonlimitvel",
    "SensorTendonpos",
    "SensorTendonvel",
    "SensorTorque",
    "SensorTouch",
    "SensorUser",
    "SensorVelocimeter",
    "Site",
    "SiteBox",
    "SiteCapsule",
    "SiteCylinder",
    "SiteEllipsoid",
    "SiteSphere",
    "Size",
    "Spatial",
    "SpatialGeom",
    "SpatialPulley",
    "SpatialSite",
    "Statistic",
    "Tendon",
    "TendonJoint",
    "Texture",
    "TextureBuiltIn",
    "Visual",
    "VisualGlobal",
    "VisualHeadlight",
    "VisualMap",
    "VisualQuality",
    "VisualRGBA",
    "VisualScale",
    "WorldBody",
]
