from __future__ import annotations

from copy import deepcopy
from typing import Literal

from pydantic import Field

from mujoco_mojo.base import XMLModel
from mujoco_mojo.mjcf.mujoco_attr.body_attr.geom import GeomBase
from mujoco_mojo.typing import SelfCollide, Vec2, Vec3, Vec5

__all__ = ["FlexContact"]


class FlexContact(XMLModel):
    """This element adjusts the contact properties of the flex. It is mostly identical to geom contact properties, with some extensions specific to flexes."""

    tag = "contact"

    attributes = (
        "contype",
        "conaffinity",
        "condim",
        "priority",
        "friction",
        "solmix",
        "solref",
        "solimp",
        "margin",
        "gap",
        "internal",
        "selfcollide",
        "activelayers",
        "vertcollide",
        "passive",
    )

    internal: bool = False
    """Enables or disables internal collisions which prevent flex self-penetration and element inversion. Note that flex elements that have shared vertices cannot collide (or else there will be permanent contacts). In 1D and 2D, internal collision checks rely on predefined vertex-element pairs, where the vertex is treated as a sphere with the same radius as the flex. These spheres correspond to non-shared vertices of neighboring elements on the periphery of the flex. The pre-defined vertex-element pairs are generated by the model compiler automatically. In 3D, internal collision checks are performed within each tetraheron: each vertex is collided with the plane corresponding to the opposing triangle face (again using the flex radius). The resulting contacts are always created with condim 1, gap 0, margin 0. Note that internal contacts modify the behavior implied by the elasticity parameters and is recommended only for flexes where element inversion cannot be prevented. The default value of this attribute was changed from "true" to "false" in version 3.3.1."""

    selfcollide: SelfCollide = SelfCollide.AUTO
    """This determines the strategy for midphase collision pruning of element pairs belonging to the same flex. none means flex elements cannot collide with each other. narrow means narrow phase only (i.e. all pairs are checked). This is a diagnostic tool and is never a good idea in practice. bvh and sap refer to bounding volume hierarchies and sweep-and-prune (which are two different strategies for midphase collision pruning). auto selects sap in 1D and 2D, and bvh in 3D. Which strategy performs better depends on the specifics of the model. The automatic setting is just a simple rule which we have found to perform well in general."""

    vertcollide: bool = False
    """Enables or disables vertex collisions. if true, spherical geoms are added at the vertices of flex, with radius equal to the radius of the flex. These geoms can collide with other geoms and are not visible by default. If false, no additional geoms are added."""

    activelayers: int = 1
    """This only has an effect for 3D flexes. Each tetrahedron is labeled by the model compiler with an integer corresponding to (graph) distance to the outside surface of the flex. Thus outside-facing elements are in layer 0, their neighbors are in layer 1, etc. This attribute specifies how many layers will be allowed to participate in collisions. The default setting 1 means that only one layer (i.e. layer 0) can collide, with itself and with the rest of the world. This is usually sufficient, however if the outer layer is composed of small tetrahedra, another body can "pierce" it and get stuck. In that case the value should be increased."""

    contype: int = Field(
        default_factory=lambda: deepcopy(GeomBase.model_fields["contype"].default),
    )
    """Same meaning as regular geom attributes."""

    conaffinity: int = Field(
        default_factory=lambda: deepcopy(GeomBase.model_fields["conaffinity"].default),
    )
    """Same meaning as regular geom attributes."""

    condim: Literal[1, 3, 4, 6] = Field(
        default_factory=lambda: deepcopy(GeomBase.model_fields["condim"].default),
    )
    """Same meaning as regular geom attributes."""

    priority: int = Field(
        default_factory=lambda: deepcopy(GeomBase.model_fields["priority"].default),
    )
    """Same meaning as regular geom attributes."""

    friction: Vec3 = Field(
        default_factory=lambda: deepcopy(GeomBase.model_fields["friction"].default),
    )
    """Same meaning as regular geom attributes."""

    solmix: float = Field(
        default_factory=lambda: deepcopy(GeomBase.model_fields["solmix"].default),
    )
    """Same meaning as regular geom attributes."""

    solref: Vec2 = Field(
        default_factory=lambda: deepcopy(GeomBase.model_fields["solref"].default),
    )
    """Same meaning as regular geom attributes."""

    solimp: Vec5 = Field(
        default_factory=lambda: deepcopy(GeomBase.model_fields["solimp"].default),
    )
    """Same meaning as regular geom attributes."""

    margin: float = Field(
        default_factory=lambda: deepcopy(GeomBase.model_fields["margin"].default),
    )
    """Same meaning as regular geom attributes."""

    gap: float = Field(
        default_factory=lambda: deepcopy(GeomBase.model_fields["gap"].default),
    )
    """Same meaning as regular geom attributes."""

    passive: bool = False
    """When enabled, the contact is not added to the contact solver but it is instead used to compute passive (spring-damper) contact forces. All contacts, regardless of the specified condim, are frictionless (condim 1). This is an experimental feature and might change in future releases."""
